/* Automatically generated by tree-sitter v0.25.1 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 37
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACK = 1,
  anon_sym_RBRACK = 2,
  sym_name = 3,
  anon_sym_EQ = 4,
  sym_key = 5,
  aux_sym_value_token1 = 6,
  aux_sym_value_token2 = 7,
  anon_sym_DQUOTE = 8,
  aux_sym_quoted_token1 = 9,
  sym_newline = 10,
  sym_whitespace = 11,
  sym_comment = 12,
  sym_config = 13,
  sym_entry = 14,
  sym_section = 15,
  sym_assign = 16,
  sym_value = 17,
  sym_quoted = 18,
  sym_separator = 19,
  sym_empty = 20,
  aux_sym_config_repeat1 = 21,
  aux_sym_config_repeat2 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_name] = "name",
  [anon_sym_EQ] = "=",
  [sym_key] = "key",
  [aux_sym_value_token1] = "value_token1",
  [aux_sym_value_token2] = "value_token2",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_token1] = "quoted_token1",
  [sym_newline] = "newline",
  [sym_whitespace] = "whitespace",
  [sym_comment] = "comment",
  [sym_config] = "config",
  [sym_entry] = "entry",
  [sym_section] = "section",
  [sym_assign] = "assign",
  [sym_value] = "value",
  [sym_quoted] = "quoted",
  [sym_separator] = "separator",
  [sym_empty] = "empty",
  [aux_sym_config_repeat1] = "config_repeat1",
  [aux_sym_config_repeat2] = "config_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_name] = sym_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_key] = sym_key,
  [aux_sym_value_token1] = aux_sym_value_token1,
  [aux_sym_value_token2] = aux_sym_value_token2,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_token1] = aux_sym_quoted_token1,
  [sym_newline] = sym_newline,
  [sym_whitespace] = sym_whitespace,
  [sym_comment] = sym_comment,
  [sym_config] = sym_config,
  [sym_entry] = sym_entry,
  [sym_section] = sym_section,
  [sym_assign] = sym_assign,
  [sym_value] = sym_value,
  [sym_quoted] = sym_quoted,
  [sym_separator] = sym_separator,
  [sym_empty] = sym_empty,
  [aux_sym_config_repeat1] = aux_sym_config_repeat1,
  [aux_sym_config_repeat2] = aux_sym_config_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_value_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_whitespace] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_config] = {
    .visible = true,
    .named = true,
  },
  [sym_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_assign] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted] = {
    .visible = true,
    .named = true,
  },
  [sym_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_empty] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_config_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_config_repeat2] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '\n', 22,
        '\r', 1,
        '"', 18,
        '=', 10,
        '[', 5,
        ']', 7,
        '\t', 23,
        ' ', 23,
        '#', 24,
        ';', 24,
      );
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(11);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(22);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == ']') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(23);
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '[') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead == '#' ||
          lookahead == ';') ADVANCE(24);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '=') ADVANCE(11);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '=') ADVANCE(11);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ']') ADVANCE(9);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_name);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ']') ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_key);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '=') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_value_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ';') ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_value_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ';') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_value_token2);
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ';') ADVANCE(16);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_value_token2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ';') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_value_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ';') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '=') ADVANCE(11);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != ';') ADVANCE(16);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_quoted_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_quoted_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_whitespace);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 3},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 14},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 12},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 20},
  [33] = {.lex_state = 15},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 15},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_key] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
    [sym_whitespace] = ACTIONS(3),
    [sym_comment] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_config] = STATE(31),
    [sym_entry] = STATE(17),
    [sym_section] = STATE(19),
    [sym_assign] = STATE(19),
    [sym_empty] = STATE(2),
    [aux_sym_config_repeat1] = STATE(2),
    [aux_sym_config_repeat2] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [sym_key] = ACTIONS(9),
    [sym_newline] = ACTIONS(11),
    [sym_whitespace] = ACTIONS(3),
    [sym_comment] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym_entry] = STATE(16),
    [sym_section] = STATE(19),
    [sym_assign] = STATE(19),
    [sym_empty] = STATE(5),
    [aux_sym_config_repeat1] = STATE(5),
    [aux_sym_config_repeat2] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(7),
    [sym_key] = ACTIONS(9),
    [sym_newline] = ACTIONS(11),
    [sym_whitespace] = ACTIONS(3),
    [sym_comment] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(11), 1,
      sym_newline,
    ACTIONS(13), 1,
      sym_comment,
    STATE(6), 2,
      sym_empty,
      aux_sym_config_repeat1,
    ACTIONS(17), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_key,
  [19] = 7,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      sym_key,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      aux_sym_config_repeat2,
    STATE(16), 1,
      sym_entry,
    STATE(19), 2,
      sym_section,
      sym_assign,
  [42] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(21), 1,
      sym_newline,
    ACTIONS(24), 1,
      sym_comment,
    STATE(5), 2,
      sym_empty,
      aux_sym_config_repeat1,
    ACTIONS(19), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_key,
  [61] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(11), 1,
      sym_newline,
    ACTIONS(13), 1,
      sym_comment,
    STATE(5), 2,
      sym_empty,
      aux_sym_config_repeat1,
    ACTIONS(27), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_key,
  [80] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(11), 1,
      sym_newline,
    ACTIONS(13), 1,
      sym_comment,
    STATE(10), 2,
      sym_empty,
      aux_sym_config_repeat1,
    ACTIONS(27), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_key,
  [99] = 7,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      sym_key,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      aux_sym_config_repeat2,
    STATE(15), 1,
      sym_entry,
    STATE(19), 2,
      sym_section,
      sym_assign,
  [122] = 7,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(36), 1,
      sym_key,
    STATE(9), 1,
      aux_sym_config_repeat2,
    STATE(23), 1,
      sym_entry,
    STATE(19), 2,
      sym_section,
      sym_assign,
  [145] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(11), 1,
      sym_newline,
    ACTIONS(13), 1,
      sym_comment,
    STATE(5), 2,
      sym_empty,
      aux_sym_config_repeat1,
    ACTIONS(39), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_key,
  [164] = 2,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(41), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_key,
      sym_newline,
      sym_comment,
  [175] = 2,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(43), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_key,
      sym_newline,
      sym_comment,
  [186] = 2,
    ACTIONS(47), 1,
      sym_whitespace,
    ACTIONS(45), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_key,
      sym_newline,
      sym_comment,
  [197] = 2,
    ACTIONS(49), 1,
      sym_whitespace,
    ACTIONS(41), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_key,
      sym_newline,
      sym_comment,
  [208] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      sym_newline,
    ACTIONS(55), 1,
      sym_comment,
    STATE(18), 1,
      sym_separator,
  [224] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      sym_newline,
    ACTIONS(55), 1,
      sym_comment,
    STATE(18), 1,
      sym_separator,
  [240] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      sym_newline,
    ACTIONS(55), 1,
      sym_comment,
    STATE(18), 1,
      sym_separator,
  [256] = 2,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(31), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_key,
  [265] = 2,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(57), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [274] = 2,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(59), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [283] = 2,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(61), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [292] = 4,
    ACTIONS(63), 1,
      aux_sym_value_token2,
    ACTIONS(65), 1,
      anon_sym_DQUOTE,
    ACTIONS(67), 1,
      sym_whitespace,
    STATE(33), 1,
      sym_quoted,
  [305] = 4,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(53), 1,
      sym_newline,
    ACTIONS(55), 1,
      sym_comment,
    STATE(18), 1,
      sym_separator,
  [318] = 2,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(69), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [327] = 2,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(71), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_comment,
  [336] = 3,
    ACTIONS(67), 1,
      sym_whitespace,
    ACTIONS(73), 1,
      aux_sym_value_token1,
    STATE(21), 1,
      sym_value,
  [346] = 2,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(75), 1,
      sym_newline,
  [353] = 2,
    ACTIONS(67), 1,
      sym_whitespace,
    ACTIONS(77), 1,
      sym_name,
  [360] = 2,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(79), 1,
      anon_sym_EQ,
  [367] = 2,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(81), 1,
      anon_sym_RBRACK,
  [374] = 2,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
  [381] = 2,
    ACTIONS(67), 1,
      sym_whitespace,
    ACTIONS(85), 1,
      aux_sym_quoted_token1,
  [388] = 2,
    ACTIONS(67), 1,
      sym_whitespace,
    ACTIONS(87), 1,
      aux_sym_value_token2,
  [395] = 2,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(89), 1,
      sym_newline,
  [402] = 2,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(91), 1,
      anon_sym_DQUOTE,
  [409] = 2,
    ACTIONS(67), 1,
      sym_whitespace,
    ACTIONS(93), 1,
      aux_sym_value_token2,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 19,
  [SMALL_STATE(5)] = 42,
  [SMALL_STATE(6)] = 61,
  [SMALL_STATE(7)] = 80,
  [SMALL_STATE(8)] = 99,
  [SMALL_STATE(9)] = 122,
  [SMALL_STATE(10)] = 145,
  [SMALL_STATE(11)] = 164,
  [SMALL_STATE(12)] = 175,
  [SMALL_STATE(13)] = 186,
  [SMALL_STATE(14)] = 197,
  [SMALL_STATE(15)] = 208,
  [SMALL_STATE(16)] = 224,
  [SMALL_STATE(17)] = 240,
  [SMALL_STATE(18)] = 256,
  [SMALL_STATE(19)] = 265,
  [SMALL_STATE(20)] = 274,
  [SMALL_STATE(21)] = 283,
  [SMALL_STATE(22)] = 292,
  [SMALL_STATE(23)] = 305,
  [SMALL_STATE(24)] = 318,
  [SMALL_STATE(25)] = 327,
  [SMALL_STATE(26)] = 336,
  [SMALL_STATE(27)] = 346,
  [SMALL_STATE(28)] = 353,
  [SMALL_STATE(29)] = 360,
  [SMALL_STATE(30)] = 367,
  [SMALL_STATE(31)] = 374,
  [SMALL_STATE(32)] = 381,
  [SMALL_STATE(33)] = 388,
  [SMALL_STATE(34)] = 395,
  [SMALL_STATE(35)] = 402,
  [SMALL_STATE(36)] = 409,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_separator, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_config_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_config_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_config_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_separator, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_config_repeat2, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_config_repeat2, 2, 0, 0), SHIFT_REPEAT(28),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_config_repeat2, 2, 0, 0), SHIFT_REPEAT(29),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_separator, 3, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty, 3, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assign, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [83] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_dunstrc(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
